name: Test and Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test Docker Compose compatibility
      run: |
        python scripts/test_docker_compose.py
        
    - name: Start services with Docker Compose
      run: |
        # Set environment variables for testing
        export MEILI_MASTER_KEY=test_key_for_ci
        export MEILI_ENV=development
        
        # Start services in detached mode
        docker compose up -d
        
        # Show running containers and ports
        echo "Docker containers status:"
        docker compose ps
        
        # Validate port configuration
        python scripts/validate_docker_ports.py
        
    - name: Wait for services to be healthy
      run: |
        # Install requests for health check script
        pip install requests
        
        # Set environment variables for health checks
        export MEILI_URL=http://localhost:7700
        export API_BASE_URL=http://localhost:8001
        export MEILI_MASTER_KEY=test_key_for_ci
        
        # Run comprehensive health checks with extended timeout
        python scripts/test_health_checks.py
        
        # Additional manual verification
        echo "Final service verification..."
        timeout 60 bash -c 'until curl -s http://localhost:7700/health > /dev/null; do sleep 1; done'
        timeout 60 bash -c 'until curl -s http://localhost:8001/health > /dev/null; do sleep 1; done'
        echo "All services confirmed healthy!"
        
    - name: Configure test environment
      run: |
        # Create a symlink or update test configuration to use the correct port
        # Since Docker Compose maps API to port 8001, but tests expect 8000
        # We'll override the API_BASE_URL for tests
        export API_BASE_URL=http://localhost:8001
        
    - name: Run simple health tests
      run: |
        # Run simple connectivity tests first
        python tests/test_simple_health.py
        
    - name: Run tests
      run: |
        # Run tests with the correct API URL
        API_BASE_URL=http://localhost:8001 python -m pytest tests/test_endpoints.py -v
        
    - name: Show service logs on failure
      if: failure()
      run: |
        echo "=== Meilisearch logs ==="
        docker compose logs meilisearch
        echo "=== API logs ==="
        docker compose logs api
        
    - name: Cleanup
      if: always()
      run: |
        docker compose down -v
